import type { Metadata } from 'next';
import './globals.css';

import { Header } from '@/app/src/layout/Header';
import { Footer } from '@/app/src/layout/Footer';
import Providers from '@/app/src/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="id" className={`h-full antialiased`}>
      <body className="h-full">
        <Providers>
          <div className="min-h-screen flex flex-col bg-background text-text transition-colors duration-200">
            <Header />

            <main className="grow">{children}</main>

            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
